indexMapping={
    "properties":{
        "Series_Title":{
            "type":"text"
        },
        "Series_Title":{
            "type":"text"
        },
        "Released_Year":{
            "type":"long"
        },
        "Certificate":{
            "type":"text"
        },
        "Runtime":{
            "type":"text"
        },
        "Genre":{
            "type":"text"
        },
        "IMDB_Rating":{
            "type":"long"
        },
        "Overview":{
            "type":"text"
        },
        "Meta_score":{
            "type":"text"
        },
        "Director":{
            "type":"text"
        },
        "Star1":{
            "type":"text"
        },
        "Star2":{
            "type":"text"
        },
        "Star3":{
            "type":"text"
        },
        "Star4":{
            "type":"text"
        },
        "No_of_Votes":{
            "type":"long"
        },
        "Gross":{
            "type":"text"
        },
        "tiltle_genre":{
            "type":"text"
        },
        "title_genre_vector":{
            "type":"dense_vector",
            "dims":768,
            "index":True,
            "similarity":"l2_norm"
        },

    }
}